### ISSUE TITLE
Switching context produces errors.

### ISSUE THREAD

**Issue by offdev** [kaufland-ecommerce/esque#139]
When trying to switch to a new context, while being on an active context which is not present in the config file anymore, the switch command produces errors.

Example (problematic) config:
```
version: 1
current_context: oldctx
contexts:
  newctx:
    bootstrap_servers:
      - broker01.my-host.com:9094
      - broker02.my-host.com:9094
    security_protocol: SASL_PLAINTEXT
    sasl_params:
      mechanism: PLAIN
      user: root
      password: toor
```

Then, when executing the ctx command, I get following error:
```
$ esque ctx
ValidationException: Context oldctx does not exist. Available contexts ['newctx']
Run with `--verbose` for complete error.
```

It's a minor issue, because it is obvious, but it would still be nice to have this fixed :)
